// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.im.sdk.protocol;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 5;
    /**
     * <code>required string id = 5;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 5;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 5;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required int32 cmd = 1;
    /**
     * <code>required int32 cmd = 1;</code>
     */
    boolean hasCmd();
    /**
     * <code>required int32 cmd = 1;</code>
     */
    int getCmd();

    // required int64 create_time = 2;
    /**
     * <code>required int64 create_time = 2;</code>
     */
    boolean hasCreateTime();
    /**
     * <code>required int64 create_time = 2;</code>
     */
    long getCreateTime();

    // optional bytes body = 10;
    /**
     * <code>optional bytes body = 10;</code>
     */
    boolean hasBody();
    /**
     * <code>optional bytes body = 10;</code>
     */
    com.google.protobuf.ByteString getBody();

    // optional string clientId = 3;
    /**
     * <code>optional string clientId = 3;</code>
     */
    boolean hasClientId();
    /**
     * <code>optional string clientId = 3;</code>
     */
    java.lang.String getClientId();
    /**
     * <code>optional string clientId = 3;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    // optional string content = 6;
    /**
     * <code>optional string content = 6;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 6;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 6;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    // optional string senderId = 7;
    /**
     * <code>optional string senderId = 7;</code>
     */
    boolean hasSenderId();
    /**
     * <code>optional string senderId = 7;</code>
     */
    java.lang.String getSenderId();
    /**
     * <code>optional string senderId = 7;</code>
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();

    // optional string receiverId = 9;
    /**
     * <code>optional string receiverId = 9;</code>
     */
    boolean hasReceiverId();
    /**
     * <code>optional string receiverId = 9;</code>
     */
    java.lang.String getReceiverId();
    /**
     * <code>optional string receiverId = 9;</code>
     */
    com.google.protobuf.ByteString
        getReceiverIdBytes();
  }
  /**
   * Protobuf type {@code com.im.sdk.protocol.Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessage
      implements DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Data(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Data defaultInstance;
    public static Data getDefaultInstance() {
      return defaultInstance;
    }

    public Data getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000002;
              cmd_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000004;
              createTime_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000010;
              clientId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              content_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              senderId_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000080;
              receiverId_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000008;
              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.im.sdk.protocol.Message.internal_static_com_im_sdk_protocol_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.im.sdk.protocol.Message.internal_static_com_im_sdk_protocol_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.im.sdk.protocol.Message.Data.class, com.im.sdk.protocol.Message.Data.Builder.class);
    }

    public static com.google.protobuf.Parser<Data> PARSER =
        new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.im.sdk.protocol.Data.Cmd}
     */
    public enum Cmd
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOGIN = 0;</code>
       */
      LOGIN(0, 0),
      /**
       * <code>LOGIN_ECHO = 1;</code>
       */
      LOGIN_ECHO(1, 1),
      /**
       * <code>LOGOUT = 2;</code>
       */
      LOGOUT(2, 2),
      /**
       * <code>LOGOUT_ECHO = 3;</code>
       */
      LOGOUT_ECHO(3, 3),
      /**
       * <code>OTHER_LOGGIN = 4;</code>
       */
      OTHER_LOGGIN(4, 4),
      /**
       * <code>HEARTBEAT = 5;</code>
       */
      HEARTBEAT(5, 5),
      /**
       * <code>CHAT_TXT = 6;</code>
       */
      CHAT_TXT(6, 6),
      /**
       * <code>CHAT_TXT_ECHO = 7;</code>
       */
      CHAT_TXT_ECHO(7, 7),
      /**
       * <code>CHAT_OFFLINE_MSGS = 8;</code>
       */
      CHAT_OFFLINE_MSGS(8, 8),
      /**
       * <code>MINE_FRIENDS = 9;</code>
       */
      MINE_FRIENDS(9, 9),
      /**
       * <code>BIND_CLIENT = 10;</code>
       */
      BIND_CLIENT(10, 10),
      ;

      /**
       * <code>LOGIN = 0;</code>
       */
      public static final int LOGIN_VALUE = 0;
      /**
       * <code>LOGIN_ECHO = 1;</code>
       */
      public static final int LOGIN_ECHO_VALUE = 1;
      /**
       * <code>LOGOUT = 2;</code>
       */
      public static final int LOGOUT_VALUE = 2;
      /**
       * <code>LOGOUT_ECHO = 3;</code>
       */
      public static final int LOGOUT_ECHO_VALUE = 3;
      /**
       * <code>OTHER_LOGGIN = 4;</code>
       */
      public static final int OTHER_LOGGIN_VALUE = 4;
      /**
       * <code>HEARTBEAT = 5;</code>
       */
      public static final int HEARTBEAT_VALUE = 5;
      /**
       * <code>CHAT_TXT = 6;</code>
       */
      public static final int CHAT_TXT_VALUE = 6;
      /**
       * <code>CHAT_TXT_ECHO = 7;</code>
       */
      public static final int CHAT_TXT_ECHO_VALUE = 7;
      /**
       * <code>CHAT_OFFLINE_MSGS = 8;</code>
       */
      public static final int CHAT_OFFLINE_MSGS_VALUE = 8;
      /**
       * <code>MINE_FRIENDS = 9;</code>
       */
      public static final int MINE_FRIENDS_VALUE = 9;
      /**
       * <code>BIND_CLIENT = 10;</code>
       */
      public static final int BIND_CLIENT_VALUE = 10;


      public final int getNumber() { return value; }

      public static Cmd valueOf(int value) {
        switch (value) {
          case 0: return LOGIN;
          case 1: return LOGIN_ECHO;
          case 2: return LOGOUT;
          case 3: return LOGOUT_ECHO;
          case 4: return OTHER_LOGGIN;
          case 5: return HEARTBEAT;
          case 6: return CHAT_TXT;
          case 7: return CHAT_TXT_ECHO;
          case 8: return CHAT_OFFLINE_MSGS;
          case 9: return MINE_FRIENDS;
          case 10: return BIND_CLIENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Cmd>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Cmd>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Cmd>() {
              public Cmd findValueByNumber(int number) {
                return Cmd.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.im.sdk.protocol.Message.Data.getDescriptor().getEnumTypes().get(0);
      }

      private static final Cmd[] VALUES = values();

      public static Cmd valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Cmd(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.im.sdk.protocol.Data.Cmd)
    }

    private int bitField0_;
    // required string id = 5;
    public static final int ID_FIELD_NUMBER = 5;
    private java.lang.Object id_;
    /**
     * <code>required string id = 5;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 5;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 cmd = 1;
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>required int32 cmd = 1;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 cmd = 1;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    // required int64 create_time = 2;
    public static final int CREATE_TIME_FIELD_NUMBER = 2;
    private long createTime_;
    /**
     * <code>required int64 create_time = 2;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 create_time = 2;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    // optional bytes body = 10;
    public static final int BODY_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 10;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes body = 10;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    // optional string clientId = 3;
    public static final int CLIENTID_FIELD_NUMBER = 3;
    private java.lang.Object clientId_;
    /**
     * <code>optional string clientId = 3;</code>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string clientId = 3;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string content = 6;
    public static final int CONTENT_FIELD_NUMBER = 6;
    private java.lang.Object content_;
    /**
     * <code>optional string content = 6;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string content = 6;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 6;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string senderId = 7;
    public static final int SENDERID_FIELD_NUMBER = 7;
    private java.lang.Object senderId_;
    /**
     * <code>optional string senderId = 7;</code>
     */
    public boolean hasSenderId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string senderId = 7;</code>
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string senderId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string receiverId = 9;
    public static final int RECEIVERID_FIELD_NUMBER = 9;
    private java.lang.Object receiverId_;
    /**
     * <code>optional string receiverId = 9;</code>
     */
    public boolean hasReceiverId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string receiverId = 9;</code>
     */
    public java.lang.String getReceiverId() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receiverId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string receiverId = 9;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverIdBytes() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      cmd_ = 0;
      createTime_ = 0L;
      body_ = com.google.protobuf.ByteString.EMPTY;
      clientId_ = "";
      content_ = "";
      senderId_ = "";
      receiverId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(1, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(2, createTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(3, getClientIdBytes());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(5, getIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getContentBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getSenderIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(9, getReceiverIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(10, body_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, createTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getClientIdBytes());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getContentBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSenderIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getReceiverIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.im.sdk.protocol.Message.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.sdk.protocol.Message.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.sdk.protocol.Message.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.sdk.protocol.Message.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.sdk.protocol.Message.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.im.sdk.protocol.Message.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.im.sdk.protocol.Message.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.im.sdk.protocol.Message.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.im.sdk.protocol.Message.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.im.sdk.protocol.Message.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.im.sdk.protocol.Message.Data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.im.sdk.protocol.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.im.sdk.protocol.Message.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.im.sdk.protocol.Message.internal_static_com_im_sdk_protocol_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.im.sdk.protocol.Message.internal_static_com_im_sdk_protocol_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.im.sdk.protocol.Message.Data.class, com.im.sdk.protocol.Message.Data.Builder.class);
      }

      // Construct using com.im.sdk.protocol.Message.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        clientId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        senderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        receiverId_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.im.sdk.protocol.Message.internal_static_com_im_sdk_protocol_Data_descriptor;
      }

      public com.im.sdk.protocol.Message.Data getDefaultInstanceForType() {
        return com.im.sdk.protocol.Message.Data.getDefaultInstance();
      }

      public com.im.sdk.protocol.Message.Data build() {
        com.im.sdk.protocol.Message.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.im.sdk.protocol.Message.Data buildPartial() {
        com.im.sdk.protocol.Message.Data result = new com.im.sdk.protocol.Message.Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.senderId_ = senderId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.receiverId_ = receiverId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.im.sdk.protocol.Message.Data) {
          return mergeFrom((com.im.sdk.protocol.Message.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.im.sdk.protocol.Message.Data other) {
        if (other == com.im.sdk.protocol.Message.Data.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        if (other.hasClientId()) {
          bitField0_ |= 0x00000010;
          clientId_ = other.clientId_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000020;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasSenderId()) {
          bitField0_ |= 0x00000040;
          senderId_ = other.senderId_;
          onChanged();
        }
        if (other.hasReceiverId()) {
          bitField0_ |= 0x00000080;
          receiverId_ = other.receiverId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasCmd()) {
          
          return false;
        }
        if (!hasCreateTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.im.sdk.protocol.Message.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.im.sdk.protocol.Message.Data) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 5;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 5;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 5;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 5;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 5;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 5;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required int32 cmd = 1;
      private int cmd_ ;
      /**
       * <code>required int32 cmd = 1;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 cmd = 1;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>required int32 cmd = 1;</code>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000002;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cmd = 1;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = 0;
        onChanged();
        return this;
      }

      // required int64 create_time = 2;
      private long createTime_ ;
      /**
       * <code>required int64 create_time = 2;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 create_time = 2;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>required int64 create_time = 2;</code>
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000004;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 create_time = 2;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes body = 10;
      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes body = 10;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes body = 10;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>optional bytes body = 10;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes body = 10;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000008);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      // optional string clientId = 3;
      private java.lang.Object clientId_ = "";
      /**
       * <code>optional string clientId = 3;</code>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string clientId = 3;</code>
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientId = 3;</code>
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientId = 3;</code>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientId = 3;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        clientId_ = value;
        onChanged();
        return this;
      }

      // optional string content = 6;
      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 6;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string content = 6;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 6;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 6;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 6;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000020);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 6;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        content_ = value;
        onChanged();
        return this;
      }

      // optional string senderId = 7;
      private java.lang.Object senderId_ = "";
      /**
       * <code>optional string senderId = 7;</code>
       */
      public boolean hasSenderId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string senderId = 7;</code>
       */
      public java.lang.String getSenderId() {
        java.lang.Object ref = senderId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          senderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string senderId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        java.lang.Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string senderId = 7;</code>
       */
      public Builder setSenderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string senderId = 7;</code>
       */
      public Builder clearSenderId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        senderId_ = getDefaultInstance().getSenderId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string senderId = 7;</code>
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        senderId_ = value;
        onChanged();
        return this;
      }

      // optional string receiverId = 9;
      private java.lang.Object receiverId_ = "";
      /**
       * <code>optional string receiverId = 9;</code>
       */
      public boolean hasReceiverId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string receiverId = 9;</code>
       */
      public java.lang.String getReceiverId() {
        java.lang.Object ref = receiverId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          receiverId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string receiverId = 9;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverIdBytes() {
        java.lang.Object ref = receiverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string receiverId = 9;</code>
       */
      public Builder setReceiverId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        receiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiverId = 9;</code>
       */
      public Builder clearReceiverId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        receiverId_ = getDefaultInstance().getReceiverId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiverId = 9;</code>
       */
      public Builder setReceiverIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        receiverId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.im.sdk.protocol.Data)
    }

    static {
      defaultInstance = new Data(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.im.sdk.protocol.Data)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_im_sdk_protocol_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_im_sdk_protocol_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\023com.im.sdk.protocol\"\307\002\n" +
      "\004Data\022\n\n\002id\030\005 \002(\t\022\013\n\003cmd\030\001 \002(\005\022\023\n\013create" +
      "_time\030\002 \002(\003\022\014\n\004body\030\n \001(\014\022\020\n\010clientId\030\003 " +
      "\001(\t\022\017\n\007content\030\006 \001(\t\022\020\n\010senderId\030\007 \001(\t\022\022" +
      "\n\nreceiverId\030\t \001(\t\"\271\001\n\003Cmd\022\t\n\005LOGIN\020\000\022\016\n" +
      "\nLOGIN_ECHO\020\001\022\n\n\006LOGOUT\020\002\022\017\n\013LOGOUT_ECHO" +
      "\020\003\022\020\n\014OTHER_LOGGIN\020\004\022\r\n\tHEARTBEAT\020\005\022\014\n\010C" +
      "HAT_TXT\020\006\022\021\n\rCHAT_TXT_ECHO\020\007\022\025\n\021CHAT_OFF" +
      "LINE_MSGS\020\010\022\020\n\014MINE_FRIENDS\020\t\022\017\n\013BIND_CL" +
      "IENT\020\nB\036\n\023com.im.sdk.protocolB\007Message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_im_sdk_protocol_Data_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_im_sdk_protocol_Data_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_im_sdk_protocol_Data_descriptor,
              new java.lang.String[] { "Id", "Cmd", "CreateTime", "Body", "ClientId", "Content", "SenderId", "ReceiverId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
